---
# bring stack down
- hosts:  loadbalancer
  become: true
  tasks:
    - name: Stop nginx
      service: name=nginx state=stopped

- hosts:  webserver
  become: true
  tasks:
    - name: Stop Apache2
      service: name=apache2 state=stopped

# Restart mysql
- hosts:  database
  become: true
  tasks:
    - name: Restart mysql
      service: name=mysql state=restarted

# Bring stack up
- hosts: webserver
  become: true
  tasks:
    - name: Start apache2
      service: name=apache2 state=started

- hosts: loadbalancer
  become: true
  tasks:
    - name: Start nginx
      service: name=nginx state=started
